<?php
// Sample test — auto-generated by goal.

use PHPUnit\Framework\TestCase;

class PlaceholderTest extends TestCase
{
    public function testPlaceholder(): void
    {
        $this->assertTrue(true);
    }
}
